version: '3'
services:
  postgres:
    build:
      context: .
    command: postgres -c hba_file=/etc/pg_hba.conf
    volumes:
      - ./pg_hba.conf:/etc/pg_hba.conf
      - ./:/download
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ebdb
    ports:
      - "5432:5432"
