version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: root@xyz.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    depends_on:
      - postgres
  postgres:
    build:
      context: .
    command: postgres -c hba_file=/etc/pg_hba.conf
    volumes:
      - ./pg_hba.conf:/etc/pg_hba.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ebdb
    ports:
      - "5432:5432"